using System;
using System.Reflection;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
[assembly: AssemblyCopyrightAttribute("Copyright (c) 2014, Charles Bryant")]
[assembly: AssemblyCompanyAttribute("decoupledlogic.wordpress.com")]
[assembly: AssemblyProductAttribute("TestPipe")]
[assembly: AssemblyTrademarkAttribute("Trademark by Charles Bryant")]
[assembly: AssemblyVersionAttribute("2.0.0")]

