// ------------------------------------------------------------------------------ 
// <auto-generated>
// This code was generated by SpecFlow (http://www.specflow.org/). SpecFlow Version:1.9.0.77
// SpecFlow Generator Version:1.9.0.0 Runtime Version:4.0.30319.18444
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------ 

#region Designer generated code

#pragma warning disable

namespace TestPipe.Demo.Features
{
	using TechTalk.SpecFlow;

	[System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
	[System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	[NUnit.Framework.TestFixtureAttribute()]
	[NUnit.Framework.DescriptionAttribute("Demo Search")]
	[NUnit.Framework.CategoryAttribute("Demo")]
	[NUnit.Framework.CategoryAttribute("Search")]
	public partial class DemoSearchFeature
	{
		private static TechTalk.SpecFlow.ITestRunner testRunner;

#line 1 "Search.feature"
#line hidden

		[NUnit.Framework.TestAttribute()]
		[NUnit.Framework.DescriptionAttribute("1. Search for Something")]
		[NUnit.Framework.CategoryAttribute("Search")]
		public virtual void _1_SearchForSomething()
		{
			TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1. Search for Something", new string[] {
                        "Search"});
#line 8
			this.ScenarioSetup(scenarioInfo);
#line 9
			testRunner.Given("I am on the search page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
			testRunner.And("when I do a search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 11
			testRunner.When("I submit the search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 12
			testRunner.Then("results should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
			this.ScenarioCleanup();
		}

		[NUnit.Framework.TestAttribute()]
		[NUnit.Framework.DescriptionAttribute("2. Search for Something")]
		public virtual void _2_SearchForSomething()
		{
			TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2. Search for Something", ((string[])(null)));
#line 14
			this.ScenarioSetup(scenarioInfo);
#line 15
			testRunner.Given("I am on the search page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 16
			testRunner.And("when I do a search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 17
			testRunner.When("I submit the search", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 18
			testRunner.Then("results should be displayed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
			this.ScenarioCleanup();
		}

		[NUnit.Framework.TestFixtureSetUpAttribute()]
		public virtual void FeatureSetup()
		{
			testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
			TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Demo Search", "In order to find what I am looking for\r\nAs a user\r\nI want to be able to search", ProgrammingLanguage.CSharp, new string[] {
                        "Demo",
                        "Search"});
			testRunner.OnFeatureStart(featureInfo);
		}

		[NUnit.Framework.TestFixtureTearDownAttribute()]
		public virtual void FeatureTearDown()
		{
			testRunner.OnFeatureEnd();
			testRunner = null;
		}

		public virtual void ScenarioCleanup()
		{
			testRunner.CollectScenarioErrors();
		}

		public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
		{
			testRunner.OnScenarioStart(scenarioInfo);
		}

		[NUnit.Framework.TearDownAttribute()]
		public virtual void ScenarioTearDown()
		{
			testRunner.OnScenarioEnd();
		}

		[NUnit.Framework.SetUpAttribute()]
		public virtual void TestInitialize()
		{
		}
	}
}

#pragma warning restore

#endregion Designer generated code